language: php

sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

cache:
  directories:
    - .phpunit
    - $HOME/.composer/cache

branches:
  only:
    - master
    - dev
    - /^\d+\.\d+$/
    - /^feature\/.*$/

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env: SYMFONY_VERSION=3.2.*
    - php: 5.5
      env: SYMFONY_VERSION=3.3.*
    - php: 5.5
      env: SYMFONY_VERSION=3.4.*
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    - php: 5.6
      env: SYMFONY_VERSION=3.3.*
    - php: 5.6
      env: SYMFONY_VERSION=3.4.*
    - php: 7.0
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 7.1
      env: SF_4="true"
    - php: hhvm
      env: SYMFONY_DEPRECATIONS_HELPER=weak
  allow_failures:
      - php: nightly

before_install:
    - phpenv config-rm xdebug.ini
    - if [ "$COVERAGE" != "true" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - composer self-update
    - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "3.0.*" ] && [ "$SYMFONY_VERSION" != "2.8.*" ] && [ "$SYMFONY_VERSION" != "2.7.*" ]; then sed -i "/dunglas\/api-bundle/d;/symfony\/serializer/d" composer.json; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$SF_4" == "true" ]; then composer config minimum-stability dev; fi
    - if [ "$SF_4" == "true" ]; then composer require symfony/symfony:4.0.* --dev --no-update; fi
    - if [ "$SF_4" == "true" ]; then composer require friendsofsymfony/rest-bundle:dev-master --dev --no-update; fi

install: composer update $COMPOSER_FLAGS --prefer-stable

script:
  - php ./phpunit
